=== Tukenbayev/epamJLabs/xmlparser/aircompanyXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.bekair.com"
        xmlns:company="http://www.bekair.com">

    <element name="aircompany">
        <complexType>
            <sequence>
                <element name="planes" type="company:Planes" minOccurs="1" maxOccurs="1"/>
                <element name="departments" type="company:Departments" minOccurs="1" maxOccurs="1"/>
            </sequence>
            <attribute name="name" type="string" use="required"/>
        </complexType>
    </element>

    <complexType name="Planes">
        <sequence>
            <element name="plane" type="company:Plane"/>
        </sequence>
    </complexType>

    <complexType name="Plane">
        <attribute name="model" use="required">
            <simpleType>
                <restriction base="string">
                    <enumeration value="IL86"></enumeration>
                    <enumeration value="SuperJet100"></enumeration>
                    <enumeration value="TU134"></enumeration>
                    <enumeration value="TU154"></enumeration>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>

    <complexType name="Departments">
        <sequence>
            <element name="department" type="company:Department" minOccurs="1" maxOccurs="2"/>
        </sequence>
    </complexType>

    <complexType name="Department">
        <sequence>
            <element name="staff_list" type="company:Staff" maxOccurs="1"/>
        </sequence>
        <attribute name="type" use="required">
            <simpleType>
                <restriction base="string">
                    <enumeration value="technical"></enumeration>
                    <enumeration value="flight"></enumeration>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>

    <complexType name="Staff">
        <all>
            <element name="technical_staff" type="company:TechnicalStaff"/>
            <element name="pilot" type="company:Pilot"/>
            <element name="airsteward" type="company:AirSteward"/>
        </all>
    </complexType>

    <complexType name="TechnicalStaff">
        <sequence>
            <element name="position" type="string"/>
            <element name="salary" type="int"/>
        </sequence>
    </complexType>

    <complexType name="Pilot">
        <sequence>
            <element name="position" type="string"/>
            <element name="salary" type="int"/>
        </sequence>
    </complexType>

    <complexType name="AirSteward">
        <sequence>
            <element name="position" type="string"/>
            <element name="salary" type="int"/>
        </sequence>
    </complexType>
</schema>

=== Tukenbayev/epamJLabs/XMLParser/aircompany.xml
<?xml version="1.0" encoding="UTF-8"?>
<company:aircompany name="BekAirs"
            xmlns:company="http://www.bekair.com"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="aircompanyXSD.xsd">
    <planes>
        <plane model="IL86"/>

        <plane model="SuperJet100"/>

        <plane model="TU134"/>

        <plane model="TU154"/>

        <plane model="TU154"/>

    </planes>
    <departments>
        <department type="technical">
            <staff_list>
                <technical_staff>
                    <position>Chief Engineer</position>
                    <salary>150000</salary>
                </technical_staff>
                <technical_staff>
                    <position>Assistant Chief Engineer</position>
                    <salary>90000</salary>
                </technical_staff>
                <technical_staff>
                    <position>Flight Engineer</position>
                    <salary>65000</salary>
                </technical_staff>
                <technical_staff>
                    <position>Flight Engineer</position>
                    <salary>65000</salary>
                </technical_staff>
                <technical_staff>
                    <position>Flight Engineer</position>
                    <salary>65000</salary>
                </technical_staff>
            </staff_list>
        </department>
        <department type="flight">
            <staff_list>
                <pilot>
                    <position>Chief Pilot</position>
                    <salary>180000</salary>
                </pilot>
                <pilot>
                    <position>Chief Pilot</position>
                    <salary>180000</salary>
                </pilot>
                <pilot>
                    <position>Second Pilot</position>
                    <salary>130000</salary>
                </pilot>
                <pilot>
                    <position>Second Pilot</position>
                    <salary>130000</salary>
                </pilot>
                <pilot>
                    <position>Second Pilot</position>
                    <salary>130000</salary>
                </pilot>
                <pilot>
                    <position>Second Pilot</position>
                    <salary>130000</salary>
                </pilot>
                <airsteward>
                    <position>Steward</position>
                    <salary>85000</salary>
                </airsteward>
                <airsteward>
                    <position>Steward</position>
                    <salary>85000</salary>
                </airsteward>
                <airsteward>
                    <position>Steward</position>
                    <salary>85000</salary>
                </airsteward>
                <airsteward>
                    <position>Steward</position>
                    <salary>85000</salary>
                </airsteward>
                <airsteward>
                    <position>Steward</position>
                    <salary>85000</salary>
                </airsteward>

            </staff_list>
        </department>
    </departments>

</company:aircompany>
